# Generated by Django 4.1.5 on 2023-06-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.IntegerField(choices=[(0, 'В магазине'), (1, 'Доставка'), (2, 'ПВЗ')], default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(1, 'Оплачено'), (0, 'Оплата при получении')], default=0),
        ),
    ]
